services:
  react-app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
      - react-app-node-modules:/app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  react-app-node-modules: